### ISSUE TITLE
文本转码报错

### ISSUE THREAD

**Issue by imjinjia** [IanusInferus/firefly#1]
大佬你好!

首先感谢大佬写出那么多的工具，辛苦了。
我在汉化一款游戏，游戏使用Shift_JIS编码，所以我就使用工具TransEncoding加载伪码表.tbl来转换文本，但是试了无数次依然报错。
命令行中使用编码名字就不报错，加载.tbl就抱错，.tbl使用的是源码中默认的FakeShift-JIS.tbl。

上传了自己测试的文件，大佬请过目啊，感谢！

![捕获](https://user-images.githubusercontent.com/39733455/161221337-4777a9d1-6243-4740-84cb-87d88a9321fb.PNG)
[test.zip](https://github.com/IanusInferus/firefly/files/8395762/test.zip)

**Comment by IanusInferus** [comment]
TransEncoding里面会判断源编码和目标编码是否一样，如果其中有编码是从文件加载的就会报错
已经修复了，可以试试编译最新版本

**Comment by imjinjia** [comment]
试了一下果然修复了，大佬能当天回复并解决问题，真是感激！
